name: Style

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install format dependencies
      run: |
        brew install clang-format
        pip3 install cmake_format==0.6.11 pyyaml

    - name: configure
      run: cmake -Hall -Bbuild

    - name: check style
      run: cmake --build build --target check-format
