name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CC: /usr/bin/gcc-10
  CXX: /usr/bin/g++-10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install GCC 10
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10

    - name: configure
      run: cmake -Hall -Bbuild
        -DWARNINGS_AS_ERRORS:BOOL=ON
        -DCMAKE_BUILD_TYPE:STRING=Debug

    - name: build
      run: cmake --build build --config Debug -j4
